### PR TITLE
prepare your Linux Ubuntu like

### PR DESCRIPTION
**Pull request by kaueMarques**

### CODE REVIEW

**Comment by vivekashok1221** [comment]
Hello @kaueMarques ,
can you explain why you have included a shell script?
IMO, `pip install -r requirements.txt` is better

**Comment by kaueMarques** [comment]
oh, sorry, I make this shell script to be more easy the installation. The shell will install to a python if a person don't have installed in your computer.
but i think that is important check if python is installed

**Comment by kaueMarques** [comment]
@codephile1221 Did you you like the idea ? Is a good way verify the python installation

**Comment by vivekashok1221** [comment]
I don't think creating a script to automatically install dependencies is a good idea.
doing `pip install -r requirements.txt` will suffice.
I appreciate your enthusiasm and interest in my project, however, I don't want to go forward with it.

**Comment by kaueMarques** [comment]
No problem, your project is really awesome. I have a question about it, will you implement the dice system?

**Comment by vivekashok1221** [comment]
My project is "ok", lol. 

I haven't thought of implementing such a system as this is a bot I run in my personal server with my friends and I don't see it being used.

**Comment by kaueMarques** [comment]
Normal, sometimes I did this kind of projects too, it's funny and help us to think more 😁

**Pull request closed without merging**
